name: burency_demo
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0" # Flutter 3.7.0

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  cupertino_icons: ^1.0.2
  font_awesome_flutter: 9.2.0

  animated_text_kit: 4.2.2
  getwidget: 3.0.1
  simple_animations: 4.0.1
  flutter_spinkit: 5.1.0
  flash: 2.0.3+2
  shimmer: 2.0.0
  flutter_svg: 1.1.6
  timeago: 3.3.0
  # web_smooth_scroll: 1.1.0
  # dropdown_search: 5.0.2

  ### Services/State Management
  get: 4.6.5
  ### Firebase Stack
  firebase_core: 2.4.1
  firebase_auth: 4.2.5
  cloud_firestore: 4.3.1
  cloud_functions: 4.0.7
  google_sign_in: 5.4.3
  flutter_facebook_auth: 5.0.7
  sign_in_with_apple: 4.3.0
  crypto: 3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  # To generate gen_l10n/app_localizations.dart, run on cmd:
  # > flutter gen-l10n
  generate: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/icons/snackbar/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Thin.ttf
          weight: 100
        - asset: assets/fonts/Montserrat-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Montserrat-Black.ttf
          weight: 900
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 900
