// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8RxORQ1c23SyZh8r10aXXCL9zH1IPjHM',
    appId: '1:147865310220:web:dee7fe2e951d8a44edca29',
    messagingSenderId: '147865310220',
    projectId: 'burencydemo',
    authDomain: 'burencydemo.firebaseapp.com',
    storageBucket: 'burencydemo.appspot.com',
    measurementId: 'G-73ZL02S2NR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2yXYQMO5ynlFqRskAtm7s__khKHMoI0I',
    appId: '1:147865310220:android:3d01c842e9f1ff31edca29',
    messagingSenderId: '147865310220',
    projectId: 'burencydemo',
    storageBucket: 'burencydemo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfLNIafrs6OqQyEK0jEeI_0EL5cQh7BUY',
    appId: '1:147865310220:ios:74994dc3cc5b3cebedca29',
    messagingSenderId: '147865310220',
    projectId: 'burencydemo',
    storageBucket: 'burencydemo.appspot.com',
    iosClientId: '147865310220-tek3iut8ult1f0g4f351iek989tj5l61.apps.googleusercontent.com',
    iosBundleId: 'com.example.burencyDemo',
  );
}
